import type { Employee } from "../../types/employee";
import type { TableConfig } from "../../types/table";


export const employees = [
    {
        id: 1,
        name: "John Smith",
        email: "john.smith@company.com",
        department: "engineering",
        role: "frontend",
        salary: 95000,
        projects: 3,
        joinDate: "2021-03-15",
        skills: ["react", "typescript", "graphql"],
        address: {
            city: "bangalore",
            state: "KA",
            country: "India",
        },
        performanceRating: 4.8,
        isActive: true,
    },
    {
        id: 2,
        name: "Emily Davis",
        email: "emily.davis@company.com",
        department: "design",
        role: "designer",
        salary: 82000,
        projects: 5,
        joinDate: "2020-06-12",
        skills: ["react", "figma"],
        address: {
            city: "mumbai",
            state: "MH",
            country: "India",
        },
        performanceRating: 4.6,
        isActive: true,
    },
    {
        id: 3,
        name: "Michael Brown",
        email: "michael.brown@company.com",
        department: "finance",
        role: "manager",
        salary: 120000,
        projects: 7,
        joinDate: "2019-11-08",
        skills: ["excel", "aws"],
        address: {
            city: "delhi",
            state: "DL",
            country: "India",
        },
        performanceRating: 4.9,
        isActive: false,
    },
    {
        id: 4,
        name: "Sarah Wilson",
        email: "sarah.wilson@company.com",
        department: "engineering",
        role: "backend",
        salary: 98000,
        projects: 4,
        joinDate: "2022-01-10",
        skills: ["java", "node", "aws"],
        address: {
            city: "hyderabad",
            state: "TS",
            country: "India",
        },
        performanceRating: 4.4,
        isActive: true,
    },
    {
        id: 5,
        name: "David Miller",
        email: "david.miller@company.com",
        department: "marketing",
        role: "manager",
        salary: 88000,
        projects: 6,
        joinDate: "2021-09-21",
        skills: ["react", "python"],
        address: {
            city: "bangalore",
            state: "KA",
            country: "India",
        },
        performanceRating: 4.2,
        isActive: false,
    },
    {
        id: 6,
        name: "Sophia Taylor",
        email: "sophia.taylor@company.com",
        department: "engineering",
        role: "fullstack",
        salary: 105000,
        projects: 2,
        joinDate: "2023-02-05",
        skills: ["react", "typescript", "node"],
        address: {
            city: "mumbai",
            state: "MH",
            country: "India",
        },
        performanceRating: 4.7,
        isActive: true,
    },
    {
        id: 7,
        name: "Daniel Moore",
        email: "daniel.moore@company.com",
        department: "hr",
        role: "manager",
        salary: 76000,
        projects: 3,
        joinDate: "2020-12-14",
        skills: ["communication", "excel"],
        address: {
            city: "delhi",
            state: "DL",
            country: "India",
        },
        performanceRating: 4.1,
        isActive: true,
    },
    {
        id: 8,
        name: "Olivia Anderson",
        email: "olivia.anderson@company.com",
        department: "engineering",
        role: "frontend",
        salary: 93000,
        projects: 5,
        joinDate: "2022-08-18",
        skills: ["react", "typescript", "node"],
        address: {
            city: "hyderabad",
            state: "TS",
            country: "India",
        },
        performanceRating: 4.5,
        isActive: true,
    },
    {
        id: 9,
        name: "James Thomas",
        email: "james.thomas@company.com",
        department: "finance",
        role: "backend",
        salary: 101000,
        projects: 4,
        joinDate: "2021-04-27",
        skills: ["java", "aws"],
        address: {
            city: "bangalore",
            state: "KA",
            country: "India",
        },
        performanceRating: 4.3,
        isActive: false,
    },
    {
        id: 10,
        name: "Emma Martinez",
        email: "emma.martinez@company.com",
        department: "design",
        role: "designer",
        salary: 79000,
        projects: 2,
        joinDate: "2023-06-01",
        skills: ["figma", "react"],
        address: {
            city: "mumbai",
            state: "MH",
            country: "India",
        },
        performanceRating: 4.8,
        isActive: true,
    },
];

export const employeeTableConfig: TableConfig<Employee> = {
    fields: [
        {
            id: "name",
            label: "Name",
            accessor: "name",
            type: "text",
            filterable: true,
            sortable: true,
        },
        {
            id: "email",
            label: "Email",
            accessor: "email",
            type: "text",
            filterable: true,
            sortable: true,
        },
        {
            id: "department",
            label: "Department",
            accessor: "department",
            type: "select",
            filterable: true,
            sortable: true,
            options: [
                { id: "engineering", label: "Engineering" },
                { id: "design", label: "Design" },
                { id: "finance", label: "Finance" },
                { id: "hr", label: "HR" },
                { id: "marketing", label: "Marketing" },
            ],
        },
        {
            id: "role",
            label: "Role",
            accessor: "role",
            type: "select",
            filterable: true,
            sortable: true,
            options: [
                { id: "frontend", label: "Frontend Developer" },
                { id: "backend", label: "Backend Developer" },
                { id: "fullstack", label: "Full Stack Developer" },
                { id: "designer", label: "UI Designer" },
                { id: "manager", label: "Engineering Manager" },
            ],
        },
        {
            id: "salary",
            label: "Salary",
            accessor: "salary",
            type: "amount",
            filterable: true,
            sortable: true,
        },
        {
            id: "projects",
            label: "Projects",
            accessor: "projects",
            type: "number",
            filterable: true,
            sortable: true,
        },
        {
            id: "joinDate",
            label: "Join Date",
            accessor: "joinDate",
            type: "date",
            filterable: true,
            sortable: true,
        },
        {
            id: "skills",
            label: "Skills",
            accessor: "skills",
            type: "multiSelect",
            filterable: true,
            sortable: false,
            options: [
                { id: "react", label: "React" },
                { id: "typescript", label: "TypeScript" },
                { id: "node", label: "Node.js" },
                { id: "graphql", label: "GraphQL" },
                { id: "java", label: "Java" },
                { id: "python", label: "Python" },
                { id: "aws", label: "AWS" },
            ],
        },
        {
            id: "city",
            label: "City",
            accessor: "address.city",
            type: "select",
            filterable: true,
            sortable: true,
            options: [
                { id: "bangalore", label: "Bangalore" },
                { id: "mumbai", label: "Mumbai" },
                { id: "hyderabad", label: "Hyderabad" },
                { id: "delhi", label: "Delhi" },
            ],
        },
        {
            id: "rating",
            label: "Rating",
            accessor: "performanceRating",
            type: "number",
            filterable: true,
            sortable: true,
        },
        {
            id: "isActive",
            label: "Active",
            accessor: "isActive",
            type: "boolean",
            filterable: true,
            sortable: true,
        },
    ],

    rows: employees,
};



